fastlane_version "1.50.0"

default_platform :ios

platform :ios do

  desc "Set up a new Mac"
  desc "To run this in readonly mode without user credentials use"
  desc "fastlane bootstrap readonly:true"
  lane :bootstrap do |options|
    unless options[:readonly]
      register_devices(devices: {
        "Felix Krause's iPhone 6s": "116307ad03065412b3084f4dc8498922e0214e73"
      })
    end

    match(type: "development", readonly: options[:readonly])
    match(type: "appstore", readonly: options[:readonly])
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number
    commit_version_bump(force: true, xcodeproj: "Themoji.xcodeproj")

    match(type: "appstore")
    gym(scheme: "Themoji")

    pilot
  end
end
