fastlane_version "1.50.0"

default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number
    commit_version_bump(force: true, xcodeproj: "Themoji.xcodeproj")

    match(type: "adhoc")
    gym(scheme: "Themoji")

    pilot
  end
end
