languages([
  "en-US",
  "de-DE"
])

devices([
  "iPhone 4s",
  "iPhone 5",
  "iPhone 6",
  "iPhone 6 Plus",
  "iPad Retina"
])

clear_previous_screenshots false # remove the '#' to clear all previously generated screenshots before creating new ones
